---
title: Cat in the Box
timezone: Europe/Berlin
collections:
  artists:
    title: Artists
    output: true
    Social:
      Facebook: 
      Twitter: 
      Youtube: 
      Instagram: 
      Soundcloud: 
      Snapchat: 
  posts:
    title: Posts
    output: true
  releases:
    title: Releases
    output: false
  uploads:
    title: Uploads
    output: true
  videos:
    title: Videos
    output: false
defaults:
- scope:
    path: ''
    type: artists
  values:
    layout: artist-detail
    Name: ''
    Photo: "/images/Leafs.jpeg"
    Facebook: ''
email: willi@yellyell.wtf
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/citb"
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
